In [52]:
import numpy as np

In [53]:
data=np.array([[1, 2, 3],
    [2, 4, 6],
    [3, 1, 0],
    [5, 2, 1],
    [0, 1, 1]])
print("dataset:\n",data)

dataset:
 [[1 2 3]
 [2 4 6]
 [3 1 0]
 [5 2 1]
 [0 1 1]]


In [54]:
v1 = data[0]
v2 = data[1]

similarity = cosine_similarity(v1, v2)
print("\nCosine Similarity between v1 and v2:", similarity)


Cosine Similarity between v1 and v2: 1.0


In [55]:
def cosine_similarity(a,b):
    dot_product=np.dot(a,b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product/(norm_a*norm_b)

In [46]:
def nearest_neighbor(query_vector, dataset):
    similarities = []

    for vector in dataset:
        sim = cosine_similarity(query_vector, vector)
        similarities.append(sim)

    best_index = np.argmax(similarities)

    return best_index, dataset[best_index], similarities

In [47]:
query = np.array([1, 2, 2])

In [48]:
index, nearest_vector, sims = nearest_neighbor(query, data)

In [49]:
print("\nQuery Vector:", query)
print("Nearest Vector:", nearest_vector)
print("Index of Nearest Vector:", index)


Query Vector: [1 2 2]
Nearest Vector: [1 2 3]
Index of Nearest Vector: 0


In [51]:
print("\nSimilarity Scores:")
for i, sim in enumerate(sims):
    print(f"Vector {i}: {sim}")


Similarity Scores:
Vector 0: 0.9799578870122228
Vector 1: 0.9799578870122228
Vector 2: 0.5270462766947299
Vector 3: 0.669438681395203
Vector 4: 0.9428090415820632
