In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report)

In [4]:
data = {
    "Age": [22,25,47,52,46,56,24,23,45,44,30,31,32,35,37,40,42,43,50,55],

    "Salary": [25000,30000,50000,65000,52000,70000,28000,27000,48000,49000,35000,36000,37000,40000,42000,45000,47000,49000,60000,68000],

    "Purchased": [0,0,1,1,1,1,0,0,1,1,0,0,0,1,1,1,1,1,1,1]
}

df = pd.DataFrame(data)

print("Dataset:")
print(df)

Dataset:
    Age  Salary  Purchased
0    22   25000          0
1    25   30000          0
2    47   50000          1
3    52   65000          1
4    46   52000          1
5    56   70000          1
6    24   28000          0
7    23   27000          0
8    45   48000          1
9    44   49000          1
10   30   35000          0
11   31   36000          0
12   32   37000          0
13   35   40000          1
14   37   42000          1
15   40   45000          1
16   42   47000          1
17   43   49000          1
18   50   60000          1
19   55   68000          1


In [5]:
print("\nDataset Info:")
print(df.info())


Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        20 non-null     int64
 1   Salary     20 non-null     int64
 2   Purchased  20 non-null     int64
dtypes: int64(3)
memory usage: 612.0 bytes
None


In [6]:
X = df[["Age", "Salary"]]
y = df["Purchased"]

print("Features (X):")
print(X.head())

print("\nTarget (y):")
print(y.head())

Features (X):
   Age  Salary
0   22   25000
1   25   30000
2   47   50000
3   52   65000
4   46   52000

Target (y):
0    0
1    0
2    1
3    1
4    1
Name: Purchased, dtype: int64


In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

X_train shape: (16, 2)
X_test shape : (4, 2)
y_train shape: (16,)
y_test shape : (4,)


In [8]:
model = LogisticRegression()
model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!


In [9]:
y_pred = model.predict(X_test)

print("Predictions:")
print(y_pred)

print("\nActual Values:")
print(y_test.values)

Predictions:
[0 1 1 0]

Actual Values:
[0 1 1 0]


In [10]:
probabilities = model.predict_proba(X_test)

print("Class Probabilities:")
print(probabilities)

purchase_prob = model.predict_proba(X_test)[:, 1]

print("\nPurchase Probabilities:")
print(purchase_prob)

Class Probabilities:
[[1.00000000e+00 1.23208846e-50]
 [0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00]
 [1.00000000e+00 3.76647977e-32]]

Purchase Probabilities:
[1.23208846e-50 1.00000000e+00 1.00000000e+00 3.76647977e-32]


In [11]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[2 0]
 [0 2]]


In [12]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

precision = precision_score(y_test, y_pred)
print("Precision:", precision)

recall = recall_score(y_test, y_pred)
print("Recall:", recall)

f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

roc_auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
print("ROC-AUC Score:", roc_auc)

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0
ROC-AUC Score: 1.0


In [13]:
y_prob = model.predict_proba(X_test)[:, 1]

y_pred_05 = (y_prob >= 0.5).astype(int)
y_pred_03 = (y_prob >= 0.3).astype(int)

print("Threshold = 0.5")
print(confusion_matrix(y_test, y_pred_05))

print("\nThreshold = 0.3")
print(confusion_matrix(y_test, y_pred_03))

print("\nRecall Comparison")
print("Recall (0.5):", recall_score(y_test, y_pred_05))
print("Recall (0.3):", recall_score(y_test, y_pred_03))

Threshold = 0.5
[[2 0]
 [0 2]]

Threshold = 0.3
[[2 0]
 [0 2]]

Recall Comparison
Recall (0.5): 1.0
Recall (0.3): 1.0


# Threshold Recommendation Memo

## Objective
Build a binary classifier to predict customer purchase behavior and select an optimal decision threshold based on business cost.

## Model Used
Logistic Regression was used to classify customers based on Age and Salary.

## Default Threshold
The initial model used a threshold of 0.5.

## Business Cost Assumption
- False Negative (Missed buyer) = High cost
- False Positive (Wrong contact) = Lower cost

## Analysis
Reducing the threshold increases recall, meaning more potential buyers are captured. However, it also increases false positives.

Increasing the threshold increases precision but may miss potential buyers.

## Final Decision
A threshold of 0.3 is recommended.

## Reason
Since missing a buyer is more expensive than contacting a non-buyer, recall is prioritized over precision.

## Expected Outcome
- Higher recall
- More customer reach
- Acceptable increase in false positives

## Conclusion
The model is optimized for business impact rather than just accuracy.